### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dbbk** [ember-cli/ember-cli-preprocess-registry#24]
It looks like quite a bit of work has been done on this since the last release in Feb 2017. Will there be a new release tagged soon?

I mention this because I've been trying to enable css-clean level 2 and I don't _think_ that is possible with Ember until this gets updated.

Thanks!

**Comment by stefanpenner** [comment]
@rwjblue looks like you cut 4.0.0-beta.1 any known issues to cut 4.0.0 stable? If so, mind listing the?

**Comment by jrjohnson** [comment]
Friendly bump on this. It would be nice to get rid of the `warning ember-cli > ember-cli-preprocess-registry > broccoli-funnel > exists-sync@0.0.4: Please replace with usage of fs.existsSync` warning in our apps.

**Comment by Turbo87** [comment]
v3.2.0 was released which should fix the warning, but due to https://github.com/ember-cli/ember-cli-preprocess-registry/issues/46 he had to "hide" the release for now. should be fixed in the next couple of days once #48 is merged.
