### ISSUE TITLE
Regular Expression Denial of Service in a dependency

### ISSUE THREAD

**Issue by mileslane** [ember-cli/ember-cli-preprocess-registry#62]
Regular Expression Denial of Service
│ Package       │ clean-css                                                    
│ Patched in    │ >=4.1.11
│ Path          │ ember-cli > ember-cli-preprocess-registry > broccoli-clean-css > clean-css-promise > clean-css

**Comment by stefanpenner** [comment]
The latest version of this library does not appear to have a dependency on broccoli-clean-css: https://github.com/ember-cli/ember-cli-preprocess-registry/blob/master/package.json#L28-L31

**Comment by stefanpenner** [comment]
Looks like ember-cli still depends on the 3x version.

**Comment by rwjblue** [comment]
@stefanpenner see https://github.com/ember-cli/ember-cli/issues/8457 for details on what we need to do to update to the latest version.

**Comment by gorner** [comment]
Have been noticing this error recently as well, and I understand there have been some issues with bumping broccoli-clean-css in a non-breaking way, per https://github.com/ember-cli/ember-cli-preprocess-registry/pull/27#discussion_r260734362.

Would it make sense to release a v4.0.0 (or 4.0.1) that includes these changes, and target the current master (without clear-css) for v5?

**Comment by kategengler** [comment]
v5.0.0 no longer uses clean-css
