### ISSUE TITLE
clean-css 4.x compatibility

### ISSUE THREAD

**Issue by dustinsoftware** [ember-cli/ember-cli-preprocess-registry#71]
I'm running in to a bug with `clean-css` and Node 12 that appears to affect `3.x` but not `4.x` versions of that library. The issue is specifically around `clean-css` aggressively re-ordering and merging style definitions, which breaks some css modules in our project using the `composes` keyword. I haven't filed an issue with `clean-css` because it looks like `4.x` is the actively maintained branch.

The current dependency graph:
`ember-cli-preprocess-registry@3.3.0` > `broccoli-clean-css: ^1.1.0` > `clean-css-promise@0.1.0` > `clean-css: ^3.4.5`

If I pin to `broccoli-clean-css@2.0.1` via yarn resolutions, I can confirm that the issue does not occur anymore.

`broccoli-clean-css@2.0.1` > `clean-css-promise: ^2.0.1` > `clean-css: ^4.0.4`

I realize that `ember-cli-preprocess-registry@4` (which was unpublished) does not include clean-css anymore; but in the meantime can a version be issued that bumps the `clean-css` dependency?  I also could fork `ember-cli-preprocess-registry` instead but would prefer to have the issue resolved so others updating to Node 12 don't run into surprising issues like we did...

**Comment by oliverlangan** [comment]
This is also affecting our project, specifically https://github.com/jakubpawlowicz/clean-css/issues/806

Looking at the 4.0 release of this process, though, I no longer see `broccoli-clean-css` as a dependency. Is it now loaded via some other mechanism?

**Comment by kategengler** [comment]
Closing since as of 5.0, this project no longer uses clean-css. 

`ember-cli-clean-css` is an addon that will provide the behavior in ember projects going forward.
